language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install .
  - pip install pytest-cov coveralls pycodestyle
  - pip install flask pygments  # for server component tests
  - bin/build_js_bundle.sh complete
  - pip list
  - pip show orca

script:
  - pycodestyle orca
  - py.test --cov orca --cov-report term-missing

after_success:
  - coveralls
